/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package presentacion;

import java.awt.Color;
import javax.swing.BorderFactory;
import javax.swing.JLabel;

/**
 *
 * @author Usuario
 */
public class VentanaDificil extends javax.swing.JFrame {

    private ControladorDificil control;
    private Modelo modelo;

    /**
     * Creates new form VentanaFacil
     */
    public VentanaDificil(Modelo aThis) {
        modelo = aThis;
        initComponents();
        crearCeldas();
        capturarEventos();

    }

    public Modelo getModelo() {
        return modelo;
    }

    public ControladorDificil getControl() {
        if (control == null) {
            control = new ControladorDificil(this);
        }
        return control;
    }
    private JLabel lblTablero[][];

    public JLabel[][] getLblTablero() {
        return lblTablero;
    }

    /**
     * Creates new form VentanaDificil
     */
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Simplified Arabic", 0, 18)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("NIVEL DIFICIL FORMA PAREJAS");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(86, 86, 86)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 524, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(100, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(456, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    // End of variables declaration//GEN-END:variables

    private void crearCeldas() {
        int x = 60;
        int y = 80;
        int ix = 70;
        int iy = 80;
        lblTablero = new JLabel[5][12];
        for (int i = 0; i < 5; i++) {
            for (int j = 0; j < 12; j++) {

                lblTablero[i][j] = new javax.swing.JLabel();
                lblTablero[i][j].setFont(new java.awt.Font("Tahoma", 0, 48)); // NOI18N
                lblTablero[i][j].setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
                lblTablero[i][j].setBorder(BorderFactory.createLineBorder(Color.red));
                lblTablero[i][j].setBounds(x + j * ix, y + i * iy, 60, 70); //inr x=70, y=80
                getContentPane().add(lblTablero[i][j]);
                lblTablero[i][j].setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/20.jpg")));
                //Colocamos un identificador
                lblTablero[i][j].setName("" + i + "," + j);
            }
        }

    }

    private void capturarEventos() {
        //Capturamos eventos
        for (int i = 0; i < 5; i++) {
            for (int j = 0; j < 12; j++) {
                lblTablero[i][j].addMouseListener(getControl());
            }
        }
    }
}
